package com.gdn.x.productcategorybase;

public enum CategoryChangeEventType {

  ACTIVATE_DEACTIVATE_CHANGE,
  CATEGORY_NAME_CHANGE,
  DATA_CHANGE,
  CATEGORY_MAPPING_CHANGE,
  CATEGORY_OSC_MAPPING_CHANGE,
  CATEGORY_HIERARCHY_CHANGE,
  HALAL_CATEGORY_CHANGE,
  DISPLAY_CHANGE;
}
