package com.gdn.x.productcategorybase;

public enum ProductMigrationType {
  COMMON_IMAGE_MIGRATION,
  GFS_TO_GCS_SOURCE_IMAGE_MIGRATION,
  GFS_TO_GCS_FINAL_IMAGE_MIGRATION,
  UPC_MIGRATION,
  PRODUCT_ATTRIBUTE_UPDATE,
  DELETE_MFD_TRUE_IMAGES_AND_ATTRIBUTES
}
