@Library('jenkins-ci-automation@master') _

BlibliPipeline ([
  type : 'java21',
  application : [
    tribe : "seller",
    squad : "catalog",
    service_name : "bulk-processor",
    dev_repo : "https://stash.gdn-app.com/scm/mta/bulk-processor.git",
    deployment_repo : [nonprod : "ssh://git@stash.gdn-app.com:7999/nonprod-seller-catalog/bulk-processor.git"]
  ],
   build_config: [
        java21: [
            maven_opts_value: "-Xms2g -Xmx10g",
            min_cpu: "4",
            max_cpu: "8",
            min_memory: "8Gi",
            max_memory: "16Gi"
        ],
    ],
  sonar: [
    serverId : 'sonar9-gcp'
  ],
    trivy: [
         enabled: true,
         jira: true,
         projectkey_jira: "SHEN",
         assignee_jira: "Pradeep Reddy",
         component_jira: "X-Bulk",
         release_jira: "-",
         build_breaker: false
            ]
])





