package com.gdn.x.product.enums;

public interface SolrConstants {

  String COLON = ":";
  String GROUP = "group";
  String OPEN_BRACKET = "(";
  String CLOSING_BRACKET = ")";
  String COMMA = ",";
  String COMMA_WITH_QUOTES = "\",\"";
  String QUOTES = "\"";
  String STRING_FORMATTER = "%s%s%s";
  String OFFER_PRICE_FORMATTER = "%s%s%.0f";
  String SOLR_EXPRESSION_DELIMITER = "*";
  String AND_CLAUSE = " AND ";
  String NULL_SALES_CATALOG = "-salesCatalog:*";
  String OPEN_SQUARE_BRACES = "[";
  String CLOSE_SQUARE_BRACES = "]";
  String TO_CLAUSE = " TO ";
  String SET_CLAUSE = "set";
  String ADD_CLAUSE = "add";
  String REMOVE_CLAUSE = "remove";
  String OR_CLAUSE = " OR ";
  String DOUBLE_QUOTE = "\"";
  String ASC = "asc";
  String DESC = "desc";
  String SCHEMA = "schema";
  String SOLR_FIELDS = "fields";
  String COPY_FIELDS = "copyFields";
  String DYNAMIC_FIELDS = "dynamicFields";
  String NAME = "name";
  String VERSION = "_version_";
  String STORE_ID = "STORE_ID";
  String MARK_FOR_DELETE = "MARK_FOR_DELETE";
  String SEPARATOR = "/";
  String DEST = "dest";
  String NOT_IN = "-";
  String FACET_FIELD = "facet.field";
  String FACET = "facet";
  String MM = "mm";
  String QF = "qf";
  String BQ = "bq";
  String DEF_TYPE = "defType";
  String EDISMAX = "edismax";
  String SORT_BOOST_QUERY = "query($bq, 0)";
  String COLLAPSE_QUERY_FOR_PRODUCT_SKU = "{!collapse field=productSku}";
  String IN_STORE_PROMO_TYPE = "INSTORE";
  String PREORDER_PROMO_TYPE = "PREORDER";
  String PROMO_PROMO_TYPE = "PROMO";
  String WHOLESALE_PROMO_TYPE = "WHOLESALE";
  String FREE_SAMPLE_TYPE = "FREESAMPLE";
  String BUNDLE_PRODUCT_TYPE = "BUNDLE_PRODUCT";
  String SELLING_PRICE_SORT = "sellingPrice";
  String NORMAL_PRICE_SORT = "normalPrice";
  String UPDATED_DATE_SORT = "updatedDate";
  String LESS_THAN_QUERY = "[* TO %s]";
  String GREATER_THAN_QUERY = "[%s TO *]";
  String ROUTE_KEY = "_route_";
  String PRICE_QUERY_WITH_RANGE = "[%s TO %s]";
  String SIZE_CHART_CODE = "sizeChartCode";
  String SPACE = " ";
  int HUNDRED = 100;
}
