package com.gdn.mta.bulk;

import java.util.Arrays;

import org.apache.commons.lang3.StringUtils;

public enum BulkInternalProcessType {
  STORE_COPY("STORE_COPY"),
  SALES_CATEGORY_UPDATE("SALES_CATEGORY_UPDATE"),
  INTERNAL_BULK_UPLOAD("INTERNAL_BULK_UPLOAD"),
  SUSPEND("SUSPEND"),
  CONFIGURATION("CONFIGURATION"),
  VENDOR_BULK_ASSIGNMENT("VENDOR_BULK_ASSIGNMENT"),
  DELETE_BRAND_AUTHORISATION("DELETE_BRAND_AUTHORISATION"),
  RECATEGORISATION("RECATEGORISATION"),
  GENERIC_FILE_GENERATION("GENERIC_FILE_GENERATION"),
  GENERIC_BUNDLING_FILE_GENERATION("GENERIC_BUNDLING_FILE_GENERATION"),
  VENDOR_AUTO_ASSIGNMENT("VENDOR_AUTO_ASSIGNMENT"),
  FBB_L5_CREATE("FBB_L5_CREATE"),
  RESTRICTED_KEYWORD_UPSERT("RESTRICTED_KEYWORD_UPSERT"),
  RESTRICTED_KEYWORD_DELETE("RESTRICTED_KEYWORD_DELETE"),
  BRAND_AUTH_ADD("BRAND_AUTH_ADD"),
  BULK_APPROVAL("BULK_APPROVAL"),
  BULK_REJECTION("BULK_REJECTION"),
  BRAND_AUTH_DELETE("BRAND_AUTH_DELETE"),
  BRAND_UPDATE("BRAND_UPDATE"),
  MASTER_SKU_BULK_ASSIGNEE("MASTER_SKU_BULK_ASSIGNEE"),
  MASTER_SKU_BULK_REVIEW("MASTER_SKU_BULK_REVIEW"),
  AUTO_APPROVED_PRODUCTS_BULK_ASSIGN("AUTO_APPROVED_PRODUCTS_BULK_ASSIGN"),
  BULK_PRICE_UPDATE("BULK_PRICE_UPDATE"),
  BULK_PRICE_REBATE("BULK_PRICE_REBATE"),
  BULK_PRICE_PRODUCT_TYPE_TAGGING("BULK_PRICE_PRODUCT_TYPE_TAGGING"),
  IPR_PORTAL_BULK_ADD_REVIEW("IPR_PORTAL_BULK_ADD_REVIEW"),
  BULK_SKU_LEVEL_REBATE("BULK_SKU_LEVEL_REBATE"),
  BULK_PRICE_UPDATE_NEW("BULK_PRICE_UPDATE_NEW"),
  INTERNAL_BRAND_UPDATE("INTERNAL_BRAND_UPDATE"),
  INTERNAL_BRAND_NAME_UPDATE("INTERNAL_BRAND_NAME_UPDATE");


  private final String type;

  BulkInternalProcessType(String type) {
    this.type = type;
  }

  public String getValue() {
    return type;
  }

  public static BulkInternalProcessType getInternalBulkProcessType(String process) {
    return Arrays.stream(BulkInternalProcessType.values())
        .filter(element -> StringUtils.equalsIgnoreCase(element.getValue(), process)).findAny().orElse(null);
  }
}
