package com.gdn.x.productcategorybase.enums;

public enum CategoryUpdateHistoryActivity {
  CATEGORY_NAME_CHANGED, CATEGORY_NAME_ENGLISH_CHANGED, PARENT_CATEGORY, DEFAULT_DESCRIPTION,
  DESCRIPTION_ENGLISH, LOGISTIC_ADJUSTMENT, OSC_ID_CHANGED, DANGEROUS_GOOD_LEVEL, ATTRIBUTE_MAPPING,
  GENERIC_TEMPLATE_FLAG_CHANGED, SUPPORT_DOCUMENT_CHANGE, BFB_FLAG_CHANGED, CATEGORY_ACTIVATED,
  CATEGORY_DEACTIVATED, AGE_LIMIT_CHANGED, SPECIAL_HANDLING_CHANGED, DIRECT_FLIGHT_CHANGED,
  SIZE_CHART_REQUIRED_CHANGED, WHOLESALE_CONFIGURATION, WHOLESALE_CONFIG_ACTIVATED, WHOLESALE_CONFIG_DEACTIVATED,
  BOPIS_ELIGIBLE_CHANGED
}
