package com.gdn.partners.product.analytics.model.enums;

public enum JobProcessTypes {

  SELLER_INFO_BQ_JOB, SELLER_SPECIFIC_INFO_BQ_JOB, AUTO_APPROVED_PRODUCTS_JOB, SELLER_ANALYTICS_INFO_BQ_JOB,
  IPR_PRODUCTS_JOB, PRODUCT_OPTIMISATION_JOB, PRODUCT_ATTRIBUTE_EXTRACTIONS_BQ_JOB;

}
