package com.gdn.x.mta.distributiontask.model.solr;

public interface SolrConstants {

  String DEFAULT_QUERY = "id:*";
  String COLON = ":";
  String AND = " AND ";
  String TODAY_FACET_INTERVAL = "[NOW/DAY, NOW]";
  String YESTERDAY_FACET_INTERVAL = "[NOW-1DAY/DAY, NOW/DAY]";
  String TWO_DAYS_AGO_FACET_INTERVAL = "[NOW-2DAYS/DAY, NOW-1DAY/DAY]";
  String TWO_TO_THREE_DAYS_AGO_FACET_INTERVAL = "[NOW-2DAYS/DAY, NOW-1DAY/DAY]";
  String THREE_TO_FIVE_DAYS_AGO_FACET_INTERVAL = "[NOW-4DAYS/DAY, NOW-2DAY/DAY]";
  String THREE_DAYS_AGO_FACET_INTERVAL = "[*, NOW-2DAYS/DAY]";
  String FIVE_DAYS_AGO_FACET_INTERVAL = "[*, NOW-4DAYS/DAY]";
  String NOT_APPLICABLE = "NA";
  String JKT_TIME_ZONE = "Asia/Jakarta";
  String APPROVED = "APPROVED";
  String COMMA_WITH_QUOTES = "\",\"";
  String TWO_DAYS_AGO = "_2DaysAgo";
  String TWO_UNTIL_THREE_DAYS_AGO = "between2until3daysOld";
  String THREE_UNTIL_FIVE_DAYS_AGO = "_3Till5DaysAgo";
  String MORE_THAN_5_DAYS = "moreThan5DaysAgo";
  String MORE_THAN_3_DAYS = "moreThan3Days";
  String PENDING = "contentAndImagePending";
  String CONTENT_PENDING = "contentPending";
  String IMAGE_PENDING = "imagePending";
  String ASSIGNED = "assigned";
  String UNASSIGNED = "unassigned";
  String DOUBLE_QUOTE = "\"";
  String BRAND_NOT_APPROVED = "brandNotApproved";
  String TODAY = "today";
  String YESTERDAY = "yesterday";
  String OPEN_BRACKET = "(";
  String COMMA = ",";
  String NOT_IN = "-";
  String LIKE_QUERY = "*";
  String QUERY_PRODUCT_CODE = "productCode:";
  String QUERY_PRODUCT_SKU = "productSku:";
  String CLOSE_BRACKET = ")";
  String AND_WITH_FUZZY_SEARCH = "~ AND ";
  String DOUBLE_QUOTES = "\"";
  String OR = " OR ";
  String EXTERNAL = "external";
  String TRUSTED_SELLER = "TRUSTED SELLER";
  String NOT = "-";
  String INTERNAL = "INTERNAL";
  String TO = "TO";
  String ALL = "ALL";
  String SET = "set";
  String SET_CLAUSE = "set";
  String COLLAPSE_FQ_FOR_BP_CODE = "{!collapse field=businessPartnerCode}";
  String AUTO_APPROVED = "Auto Approved";
  String OPEN_SQUARE_BRACKET = "[";
  String CLOSE_SQUARE_BRACKET = "]";
  Integer REJECTED_COUNT_GREATER_THAN_2 = 2;
  String RESTRICTED_KEYWORD = "restrictedKeyword";
  String CARET = "^";
  String DEF_TYPE = "defType";
  String EDISMAX = "edismax";
  String QUERY = "q";
  String BOOSTED_QUERY = "bq";
  String FILTER_TRUE_CLAUSE = "{!bool filter=true}";
  String FILTER_QUERY = "fq";
  String QF = "qf";
  String MM = "mm";
  int MM_VALUE = 100;
  int ROW_ZERO = 0;
  int ONE_ROW = 1;
  String IPR_PRODUCT_NOT_ASSIGNED = "-assignedTo";
  String ASSIGNED_PRESENT = "[* TO *]";
  String ASSIGNED_COUNT_QUERY = "assignedTo:*";
  String UNASSINGED_COUNT_QUERY = "-assignedTo:*";
}
