package com.gdn.mta.bulk.models;

/**
 * Created by keshashah on 24/10/16.
 */
public enum BulkProcessEntity {
  PRODUCT, ORDER, FAILED_PRODUCT, PRODUCT_VENDOR, CAMPAIGN_PRODUCT, MASTER_PRODUCT,
  SELECTED_MASTER_PRODUCTS, MASTER_SKU_IN_REVIEW_DOWNLOAD,
  REVIEW_PRODUCTS, VENDOR_FILTERED_PRODUCT, INSTANT_PICKUP_PRODUCT, CONFIGURATION_MERCHANT_SUMMARY, CONFIGURATION_CATEGORY_SUMMARY,
  RECAT_FAILED_PRODUCTS, STORE_COPY_PRODUCTS, STORE_COPY_UPLOAD_TEMPLATE, STORE_COPY_FAILED_PRODUCTS, UPDATE_SALES_CATEGORY_FAILED_PRODUCTS, BRAND_AUTHORIZATION_DOWNLOAD,
  DELETE_UPDATE_PICKUP_POINTS, MASTER_SKU_ALL_ITEMS_DOWNLOAD, MASTER_SKU_SELECTED_ITEMS_DOWNLOAD, AUTO_APPROVED_PRODUCTS_ALL_DOWNLOAD, AUTO_APPROVED_PRODUCTS_SELECTED_DOWNLOAD, BULK_PRICE_RECOMMENDATION
  ,BULK_DOWNLOAD_TAGGED_PRODUCTS , IPR_PRODUCTS_DOWNLOAD_ALL, PRODUCT_BASIC_INFO,PRODUCT_EAN
}
