@Library('jenkins-ci-automation@develop') _

BlibliPipeline ([
  type : 'java21',
  application : [
    tribe : "seller",
    squad : "catalog",
    service_name : "pcu-master-api",
    dev_repo : "https://stash.gdn-app.com/scm/mta/pcu-master-api.git",
    deployment_repo : [nonprod : "ssh://git@stash.gdn-app.com:7999/nonprod-seller-catalog/pcu-master-api.git"]
    ],
  sonar: [
    serverId : 'sonar9-gcp'
    ],
  trivy: [
    enabled: true,
    jira: true,
    projectkey_jira: "SHEN",
    assignee_jira: "Pradeep Reddy",
    component_jira: "PCU Master-API",
    release_jira: "-",
    build_breaker: false
           ]
])