package com.gdn.partners.pcu.internal.streaming.model.bulk;

/**
 * Created by govind on 28/01/2019 AD.
 */

public enum BulkProcessEntity {
  REVIEW_PRODUCTS,
  VENDOR_FILTERED_PRODUCT,
  CONFIGURATION_MERCHANT_SUMMARY,
  CONFIGURATION_CATEGORY_SUMMARY,
  SELECTED_MASTER_PRODUCTS,
  MASTER_SKU_IN_REVIEW_DOWNLOAD,
  MASTER_PRODUCT,
  STORE_COPY_PRODUCTS,
  BRAND_AUTHORIZATION_DOWNLOAD,
  MASTER_SKU_ALL_ITEMS_DOWNLOAD,
  MASTER_SKU_SELECTED_ITEMS_DOWNLOAD,
  AUTO_APPROVED_PRODUCTS_ALL_DOWNLOAD,
  AUTO_APPROVED_PRODUCTS_SELECTED_DOWNLOAD,
  IPR_PRODUCTS_DOWNLOAD_ALL,
  IPR_PRODUCTS_DOWNLOAD_SELECTED;
}
