package com.gdn.x.productcategorybase;

public enum ErrorMessage {
  ENTITY_REQUIRED_VALIDATION_FOR_UPDATE_MESSAGE("required field updatedBy or updatedDate is empty"),
  ENTITY_REQUIRED_VALIDATION_FOR_SAVE_MESSAGE("required field createdBy or createdDate is empty"),
  ENTITY_REQUIRED_CATALOG_TYPE_FOR_SAVE_MESSAGE("required field catalogType is empty"),
  ENTITY_REQUIRED_CATALOG_ID_FOR_DELETE_MESSAGE("required field catalogId is empty"),
  ENTITY_REQUIRED_PRODUCT_CATEGORY_FOR_SAVE_MESSAGE("required field productCategory is empty"),
  ENTITY_NOT_FOUND_FOR_UPDATE_MESSAGE("cannot find id"),
  CATEGORY_ID_MUST_NOT_BE_BLANK("Category id must not be blank"),
  UPC_CODE_MUST_NOT_BE_BLANK("UPC code must not be blank"),
  CATEGORY_IDS_MUST_NOT_BE_EMPTY("category IDs list cannot be null or empty"),
  CATALOG_ID_MUST_NOT_BE_BLANK("Catalog id must not be blank"),
  PRODUCT_ID_MUST_NOT_BE_BLANK("Product id must not be blank"),
  PRODUCT_ITEMS_MUST_DEFINE("Product items must define"),
  IMAGE_HASHCODE_MUST_NOT_BE_BLANK("Image hashcode must not be blank"),
  IMAGE_LOCATION_PATH_MUST_NOT_BE_BLANK("Image location path must not be blank"),
  PRODUCT_CODE_MUST_NOT_BE_BLANK("product code must not be blank"),
  ATTRIBUTE_CODES_MUST_NOT_BE_BLANK("attribute codes must not be blank"),
  ATTRIBUTE_ID_MUST_NOT_BE_BLANK("attribute_id must not be blank"),
  IMAGE_REQUEST_MUST_NOT_BE_BLANK("image request must not be blank"),
  ATTRIBUTE_CODE_MUST_NOT_BE_BLANK("attribute code must not be blank"),
  ERROR_IN_FETCHING_CATEGORY_INFO("Error in fetching category info based on id"),
  ERROR_IN_SAVING_OSC("Exception while saving the original sales category"),
  CATEGORY_CODE_MUST_NOT_BE_BLANK("Category code must not be blank"),
  INDEX_TYPE_DOES_NOT_MATCH("Index type does not match"),
  BRAND_WIP_NOT_FOUND("No such brand wip found for given brand request code"),
  BRAND_ALREADY_APPROVED(" is already there!! Please reject the added brand and use the existing active Brand."),
  MERCHANT_HISTORY_ERROR(" Merchant history should not be empty."),
  CATEGORY_HISTORY_ERROR(" Category history should not be empty."),
  MERCHANT_CODE_ERROR(" Merchant code should not be empty."),
  MERCHANT_CONFIGURATION_NOT_FOUND("Can not find merchant configuration with the merchant code : "),
  CATEGORY_CONFIGURATION_NOT_FOUND("Can not find category configuration with the category code : "),
  MERCHANT_DELETE_STATE("Merchant configuration is already in deleted state for merchant : "),
  CATEGORY_NOT_FOUND("not found category with codes : "),
  CATEGORY_NOT_PRESENT("Category not found"),
  CATEGORY_STATE_INVALID("Category is not active"),
  CATEGORY_NOT_BELONG_TO_MASTER_CATALOG("Category %s don't belong to master catalog"),
  CATEGORY_NOT_CN("Category is not leaf category"),
  PRODUCT_CATEGORY_CANT_BE_UPDATED_BECAUSE_THE_CATEGORY_IS_B2B("Product category can't be updated because the new category is b2b exclusive : "),
  CATEGORY_DELETE_STATE("Category configuration is already in deleted state for category :  "),
  IN_ACTIVE_CATEGORY_ADD_ERROR(" Can not add in-active category for categoryCode:  "),
  IN_ACTIVE_CATEGORY_UPDATE_ERROR(" Can not update in-active category for categoryCode:  "),
  IN_ACTIVE_MERCHANT_UPDATE_ERROR(" Can not update in-active merchant for merchantCode :  "),
  IN_ACTIVE_MERCHANT_ADD_ERROR(" Can not add in-active merchant for merchantCode :  "),
  MERCHANT_NOT_FOUND("not found merchant with code : "),
  SCHEDULAR_EVENT_ERROR("Error while running config mail schedulers "),
  CREATED_DATE_MUST_NOT_BE_BLANK("Created date must not be blank"),
  REVIEW_CONFIG_FLAG_INVALID("reviewConfig flag should be Pre-live or Post-live for categoryCode : "),
  REVIEW_CONFIG_FLAG_INVALID_FOR_MERCHANT("reviewConfig flag should not be other than Pre-live Post-live and Neutral for merchantCode : "),
  CATEGORY_MUST_NOT_BE_BLANK("Category should not be empty"),
  NOT_VALID_MERCHANT("Not a valid merchant to configure"),
  NOT_VALID_CATEGORY("Not a valid category to configure"),
  ERROR_UPDATING_CATEGORY_CONFIG("Something went wrong. Please try again to add category configuration"),
  ERROR_UPDATING_MERCHANT_CONFIG("Something went wrong. Please try again to add merchant configuration"),
  STORE_ID_MUST_NOT_BE_BLANK("StoreId shouldn't be blank"),
  SELLER_CODE_MUST_NOT_BE_BLANK("SellerCode shouldn't be blank"),
  REQUESTED_BRAND_CODE_MUST_NOT_BE_BLANK("Requested Brand code shouldn't be blank"),
  PREDICTED_BRAND_NAME_MUST_NOT_BE_BLANK("Predicted Brand name shouldn't be blank"),
  BRAND_CODE_MUST_NOT_BE_BLANK("Brand code shouldn't be blank"),
  IPR_REGISTRATION_NUMBER_MUST_NOT_BE_BLANK("Ipr registration number shouldn't be blank"),
  BRAND_IS_NOT_PROTECTED("Brand is not protected."),
  LOOKUP_GROUP_MUST_NOT_BE_BLANK("Lookup group shouldn't be blank"),
  UPDATED_DATE_MUST_NOT_BE_BLANK("UpdatedDate shouldn't be blank"),
  ERROR_CONFIG_TYPE("ConfigType must not be blank. Please enter valid value"),
  REVIEW_CONFIG_FLAG_ERROR(" review_config flag is already updated"),
  PRODUCT_NOT_FOUND("Product not found : "),
  NO_ACTIVE_PRODUCT_CATEGORY_FOUND("No active product category found"),
  EXISTING_AND_NEW_CATEGORY_ARE_SAME("Existing category and new category are same"),
  ITEM_NOT_FOUND_FOR_SKU_CODE("Item not found for given item code - "),
  NOT_VALID_PARAMETERS("Parameters does not have proper values"),
  ITEM_CODE_MUST_NOT_BE_BLANK("item code must not be blank"),
  RESTRICTED_KEYWORD_ERROR("Restricted Keyword list should not be empty"),
  ENTITY_REQUIRED_VALIDATION_FOR_RESTRICTED_KEYWORD("required field categoryCode and keyword both empty"),
  ATTRIBUTE_VALUE_MUST_NOT_BE_EMPTY("Attribute value must not be empty"),
  ERROR_GETTING_WHOLESALE_CONFIG("required field categoryCode or categoryId both are empty"),
  BRAND_NOT_FOUND_FOR_PRODUCT_CODE("Brand not found for productCode: "),
  EMPTY_IMAGE_LOCATION_PATH("Image location path cannot be empty or blank for product"),
  PRODUCT_SCORE_SCHEDULER_ERROR("Error while running product score schedulers "),
  VARIABLE_MUST_NOT_BE_BLANK("variable must not be blank"),
  VALUE_MUST_NOT_BE_BLANK("value must not be blank"),
  DESCRIPTION_MUST_NOT_BE_BLANK("description must not be blank"),
  VALUE_NOT_FOUND("value not found for update"),
  SYSTEM_PARAMETER_IS_NOT_FOUND("System parameter '%s' is not found for storeId '%s'"),
  GREATER_THAN_MAX_ALLOWED_SIZE_ERROR("Size is greater than maximum allowed size. [size = %s, maxAllowedSize = %s]"),
  INVALID_CATEGORY_ERROR_CODE("ERR-CAT-00001"),
  INVALID_CATEGORY_ERROR_MESSAGE("The selected category is deleted, inactive or is not a Cn category. Please select other to continue."),
  PRODUCT_CONTENT_EXPIRED("Product content is expired"),
  OSC_CODE_MUST_NOT_BE_BLANK("OSC code must not be blank"),
  OSC_SHORT_TEXT_MUST_NOT_BE_BLANK("OSC Short text must not be blank"),
  OSC_LONG_TEXT_MUST_NOT_BE_BLANK("OSC Long text must not be blank"),
  OSC_ID_MUST_NOT_BE_BLANK("OSC ID must not be blank"),
  OSC_IS_INACTIVE("The osc is inactive"),
  OSC_NOT_FOUND("No active original sales category found by ID : {}"),
  ERROR_IN_UPDATING_OSC("Exception while updating the original sales category"),
  REQUEST_ID_MUST_NOT_BE_BLANK("Request Id must not be empty"),
  VAT_FLAG_TO_UPDATE_NULL("Vat flag to update for item is null"),
  VAT_FLAG_NO_CHANGE("Vat flag for item has no changes"),
  CANNOT_DELETE_MAIN_IMAGE("Cannot delete main image"),
  IMAGE_ALREADY_EXISTS("Image already exists in the item"),
  MAX_IMAGE_REACHED("Item already has max images"),
  IMAGE_NOT_PRESENT("Image not present in item"),
  ONLY_IMAGE_IN_ITEM("Cannot delete only image in item"),
  SYSTEM_ERROR("system error"),
  STATUS_MUST_NOT_BE_EMPTY("Status must not be empty"),
  STORE_ID_MUST_NOT_BE_EMPTY ("Store id must not be empty"),
  USER_NAME_MUST_NOT_BE_EMPTY ("User name must not be empty"),
  PRODUCT_CODE_MUST_NOT_BE_EMPTY ("Product code must not be empty"),
  ACTION_CANNOT_BE_PERFORMED("Action cannot be performed"),
  MIGRATION_TYPE_MUST_NOT_BE_EMPTY ("Migration type must not be empty"),
  BRAND_NAME_MUST_NOT_BE_BLANK("Brand name shouldn't be blank"),
  REASON_MUST_NOT_BE_EMPTY("Reason shouldn't be blank"),
  BRAND_NAME_MUST_NOT_BE_BLANK_ERROR_CODE("ERR-SIZ-00012"),
  AUTH_END_DATE_MUST_NOT_BE_BEFORE_START_DATE("Authorisation end date should not be before start "
    + "date"),
  AUTH_START_OR_END_DATE_MUST_NOT_BE_NULL("Authorisation start and end date should not be null"),
  AUTH_ALREADY_PRESENT("Seller telah diotorisasi untuk brand ini."),
  PREDICTION_ID_MUST_NOT_BE_NULL_OR_EMPTY ("PredictionId must not be null or empty"),
  CATEGORY_CODE_MUST_NOT_BE_NULL_OR_EMPTY ("CategoryCode must not be null or empty"),
  CATEGORY_CODE_LIST_MUST_NOT_BE_EMPTY ("CategoryCodeList must not be empty"),
  REQUEST_LIST_MUST_NOT_BE_EMPTY ("RequestList must not be empty"),
  PREDICTION_ID_LIST_MUST_BE_NULL_OR_EMPTY ("PredictionId list must not be null or empty"),
  CANNOT_UPDATE_OR_ADD_MULTIPLE_PREDICTION_ID_AT_ONCE ("Cannot update or add multiple predictionId at once, can update only one predictionId in a request"),
  NO_PREDICTION_CATEGORY_MAPPING_FOUND_FOR_ALL_PREDICTION_IDS_GIVEN_IN_REQUEST ("No predictionCategoryMapping found for all predictionIds given in request"),
  SELLER_CODE_NOT_FOUND_IN_BRAND_AUTH_TABLE("Brand Auth mappings was not found for Seller Code : "),
  BULK_DOWNLOAD_IDS_MUST_NOT_BE_EMPTY(
    "Brand Auth download list ids must not be empty."),
  BRAND_IS_NOT_VALID_OR_NOT_PROTECTED(
    "Brand is not valid or not protected."),
  GCS_SOURCE_IMAGE_FILE_NOT_FOUND("Gcs source image file not found. filePath : %s "),
  IMAGE_DOWNLOADED_FROM_GCS_WAS_NULL("Image downloaded from GCS was null error"),
  FILE_NAME_WAS_EMPTY_WHILE_COPYING_IMAGE_FROM_SOURCE_TO_TARGET(
      "File name was empty while copying image from source to target"),
  INVALID_ID("Cannot find CategoryRestrictedKeyword by this id"),
  CATEGORY_RESTRICTED_KEYWORD_ID_NOT_FOUND("Cannot find category restricted keyword with ID : "),
  PRODUCT_CODE_LIST_MUST_NOT_BE_EMPTY("ProductCode list must not be empty"),
  CATEGORY_DO_NOT_EXISTS("%s-Kategori tidak ditemukan"),
  CATEGORY_IS_NOT_ACTIVATED("%s-Category is not activated"),
  CATEGORY_IS_NOT_LEAF("%s-Category is not leaf"),
  CATEGORY_IS_NOT_MASTER_CATEGORY("%s-Category is not master category"),
  FILE_NAME_SHOULD_NOT_BE_NULL_OR_EMPTY("File name should not be null or empty"),
  SELLER_CODE_OR_BRAND_CODE_SHOULD_NOT_BE_NULL_OR_EMPTY("Brand Code or Seller Code should not be "
    + "null or empty"),
  RESTRICTED_KEYWORD_ID_MUST_NOT_BE_EMPTY("Restricted keyword id must not be empty"),
  ACTIVITY_MUST_NOT_BE_EMPTY("Activity must not be empty"),
  BRAND_AUTH_NOT_FOUND_FOR_SELLER_AND_BRAND_CODE(
    "Brand Authorisation mappings was not found for Seller and Brand Code : "),
  KEYWORD_IDS_MUST_NOT_BE_EMPTY("Keyword Ids must not be empty"),
  PRODUCT_REQUEST_CANNOT_BE_NULL("Product Request Cannot be Null"),
  PRODUCT_VARIANT_IS_NOT_ALLOWED("Product variant cannot be created as variant creating attribute is not matching across product variants"),
  NEW_BRAND_CODE_CANNOT_BE_SAME_AS_OLD_BRAND_CODE("New brand code cannot be same as old brand code"),
  BRAND_NOT_FOUND("Brand not found : "),
  BRAND_NOT_FOUND_ERROR_CODE("ERR-SIZ-00003"),
  IMAGE_UPDATE_FAILED_FOR_PDP_EDIT_REQUEST("Image Update failed for PDP Edit Request for product "
    + "=%s"),
  EVICT_CACHE_AND_HISTORY_UPDATE_FAILED("Evicting Cache and Brand Authorisation History publish Failed"),
  NO_ITEM_FOUND_TO_CREATE_PRODUCT("No item found to create product"),
  INVALID_ADD_VARIANT_REQUEST("Invalid add variant request"),
  DIMENSION_CODE_MUST_NOT_BE_BLANK("required field dimension code is empty"),
  DIMENSION_DOES_NOT_EXIST_WITH_DIMENSION_CODE("dimension does not exist"),
  DIMENSION_ALREADY_EXISTS_ERROR_CODE("ERR-DIM-00001"),
  DIMENSION_MAPPING_DOES_NOT_EXIST_FOR_ATTRIBUTE_CODE_ERROR_CODE("ERR-DIM-00002"),
  DIMENSION_MAPPING_CANNOT_BE_EMPTY("Dimension mapping cannot be empty"),
  DIMENSION_DOES_NOT_EXIST_WITH_DIMENSION_CODE_ERROR_CODE("ERR-DIM-00003"),
  DIMENSION_MAPPING_DOES_NOT_EXIST_FOR_ATTRIBUTE_CODE("dimension mapping does not exist"),
  DIMENSION_MAPPING_FOR_SIZE_CHART_DOES_NOT_EXIST_FOR_ATTRIBUTE_CODE_ERROR_CODE("ERR-SIZ-00005"),
  DIMENSION_ALREADY_EXISTS_ERROR_MESSAGE("Dimension already exists"),
  SIZE_CHART_NAME_CANNOT_BE_BLANK("Size chart name cannot be blank"),
  SIZE_CHART_NAME_CANNOT_BE_BLANK_ERROR_CODE("ERR-SIZ-00006"),
  ATTRIBUTE_NAME_MUST_NOT_BE_BLANK("Attribute name must not be blank"),
  ATTRIBUTE_NAME_MUST_NOT_BE_BLANK_ERROR_CODE("ERR-SIZ-00008"),
  SELECTED_VALUE_TYPES_LIST_CANNOT_BE_EMPTY("Selected value types list cannot be empty"),
  SELECTED_VALUE_TYPES_LIST_CANNOT_BE_EMPTY_ERROR_CODE("ERR-SIZ-00009"),
  SELECTED_DIMENSION_LIST_CANNOT_BE_EMPTY("Selected dimension list cannot be empty"),
  SELECTED_DIMENSION_LIST_CANNOT_BE_EMPTY_ERROR_CODE("ERR-SIZ-00010"),
  SIZE_CHART_GENDER_CANNOT_BE_BLANK("Size chart gender cannot be blank"),
  SIZE_CHART_GENDER_CANNOT_BE_BLANK_ERROR_CODE("ERR-SIZ-00011"),
  GENDER_IS_INVALID("Gender is invalid"),
  GENDER_IS_INVALID_ERROR_CODE("ERR-SIZ-00013"),
  SIZE_CHART_UNIT_CANNOT_BE_BLANK("Size chart unit cannot be blank"),
  SIZE_CHART_UNIT_CANNOT_BE_BLANK_ERROR_CODE("ERR-SIZ-00014"),
  SIZE_CHART_ROWS_CANNOT_BE_EMPTY("Size chart rows cannot be Empty"),
  SIZE_CHART_ROWS_CANNOT_BE_EMPTY_ERROR_CODE("ERR-SIZ-00015"),
  SIZE_CHART_HEADER_MISMATCH("Size chart header mismatch"),
  SIZE_CHART_HEADER_MISMATCH_ERROR_CODE("ERR-SIZ-00016"),
  SIZE_CHART_NAME_ALREADY_EXISTS("Size chart already exists"),
  SIZE_CHART_NAME_ALREADY_EXISTS_ERROR_CODE("ERR-SIZ-00001"),
  SIZE_CHART_NAME_EDIT_NOT_ALLOWED_ERROR_CODE("ERR-SIZ-00023"),
  SIZE_CHART_NAME_EDIT_NOT_ALLOWED_ERROR_MESSAGE("Size Chart Name Edit Not Allowed"),
  DIMENSION_VALUE_CANNOT_BE_EMPTY("Dimension value cannot be empty"),
  DIMENSION_VALUE_CANNOT_BE_EMPTY_ERROR_CODE("ERR-SIZ-00019"),
  VALUE_TYPE_IS_NOT_SELECTED("Value type is not selected"),
  VALUE_TYPE_IS_NOT_SELECTED_ERROR_CODE("ERR-SIZ-00021"),
  SIZE_CHART_NOT_FOUND_WITH_SIZE_CHART_CODE("Size chart not found with request size chart code"),
  SIZE_CHART_NOT_FOUND_WITH_SIZE_CHART_CODE_ERROR_CODE("ERR-SIZ-00022"),
  DIMENSION_VALUE_CAN_EITHER_BE_SINGLE_OR_RANGE("Dimension value can either be single or range"),
  DIMENSION_VALUE_CAN_EITHER_BE_SINGLE_OR_RANGE_ERROR_CODE("ERR-SIZ-00028"),
  DIMENSION_VALUE_CAN_ONLY_HAVE_NUMERIC_VALUES("Dimension value can only have numeric values"),
  DIMENSION_VALUE_CAN_ONLY_HAVE_NUMERIC_VALUES_ERROR_CODE("ERR-SIZ-00024"),
  MAX_VALUE_SHOULD_BE_GREATER_THAN_MIN_VALUE("Max value should be greater than min value"),
  MAX_VALUE_SHOULD_BE_GREATER_THAN_MIN_VALUE_ERROR_CODE("ERR-SIZ-00025"),
  SIZE_CHART_INVALID_UNIT("Invalid size chart unit value"),
  SIZE_CHART_INVALID_UNIT_ERROR_CODE("ERR-SIZ-00026"),
  SIZE_CHART_NOT_FOUND_WITH_SIZE_CHART_CODE_AND_BUSINESS_PARTNER_CODE("Size chart not found with request size chart code and businessPartnerCode"),
  SIZE_CHART_CODE_CANNOT_BE_BLANK("Size chart code cannot be blank"),
  BUSINESS_PARTNER_CODE_CANNOT_BE_BLANK("Business partner code cannot be blank"),
  BUSINESS_PARTNER_CODE_CANNOT_BE_BLANK_ERROR_CODE("ERR-SIZ-00007"),
  INVALID_SIZE_CHART_CODE("Size chart tidak ditemukan, periksa kembali sesuai kode di halaman size chart"),
  INVALID_SIZE_CHART_CODE_ERROR_CODE("ERR-SIZ-00029"),
  SIZE_CHART_IS_NOT_VALID_FOR_THE_CATEGORY("Size chart yang digunakan tidak sesuai dengan kategori produk"),
  SIZE_CHART_IS_NOT_VALID_FOR_THE_CATEGORY_ERROR_CODE("ERR-SIZ-00030"),
  SIZE_ATTRIBUTE_TYPE_CANNOT_BE_CHANGED("Size attribute type cannot be changed"),
  ATTRIBUTE_TYPE_CANNOT_BE_SIZE_ATTRIBUTE("Given attribute type cannot be size attribute"),
  ATTRIBUTE_TYPE_CANNOT_BE_SIZE_ATTRIBUTE_ERROR_CODE("ERR-DIM-00003"),
  DIMENSION_MAPPING_ALREADY_EXIST_WITH_ATTRIBUTE_CODE("dimension mapping already exist with attribute code"),
  ATTRIBUTE_IMAGE_URL_MUST_NOT_BE_EMPTY("Attribute image url must not be empty"),
  VALUE_TYPE_PROVIDED_IS_WRONG("Value type provided is wrong"),
  VALUE_WITH_VALUE_TYPE_ALREADY_EXISTS_ERROR_CODE("ERR-DIM-00004"),
  VALUE_WITH_VALUE_TYPE_ALREADY_EXISTS("Value with value type already exists"),
  VALUE_TYPES_MUST_NOT_BE_EMPTY("Value types must not be empty"),
  VALUE_TYPES_CANNOT_BE_UNMAPPED("Value types cannot be unmapped"),
  VALUE_TYPE_CONFIG_IS_EMPTY("Value type config is empty"),
  ATTRIBUTE_IS_NOT_SIZE_ATTRIBUTE("attribute is not a size type attribute for mapping dimensions"),
  ATTRIBUTE_IS_NOT_SIZE_ATTRIBUTE_ERROR_CODE("ERR-SIZ-00002"),
  DIMENSION_MAPPING_ALREADY_EXIST_FOR_ATTRIBUTE_CODE("dimension mapping already exists"),
  INVALID_DIMENSION_MAPPING_UPDATE_REQUEST("Invalid dimension mapping update request"),
  VALUE_TYPES_SELECTED_IS_NOT_MAPPED_TO_ATTRIBUTE("Value types selected are not mapped to "
    + "attribute"),
  VALUE_TYPES_SELECTED_IS_NOT_MAPPED_TO_ATTRIBUTE_ERROR_CODE("ERR-SIZ-00004"),
  SELECTED_DIMENSION_AND_ROW_DIMENSION_DOES_NOT_MATCH("Selected dimension and row dimension does "
    + "not match"),
  SELECTED_DIMENSION_AND_ROW_DIMENSION_DOES_NOT_MATCH_ERROR_CODE("ERR-SIZ-00018"),
  SELECTED_VALUE_TYPE_AND_ROW_VALUE_TYPE_DOES_NOT_MATCH("Selected value type and row value type "
    + "does not match"),
  SELECTED_VALUE_TYPE_AND_ROW_VALUE_TYPE_DOES_NOT_MATCH_ERROR_CODE("ERR-SIZ-00020"),
  INVALID_HEADER_TYPE_IN_SIZE_CHART("Invalid header type in size chart"),
  INVALID_HEADER_TYPE_IN_SIZE_CHART_ERROR_CODE("ERR-SIZ-00017"),
  DUPLICATE_ATTRIBUTE_VALUE_PRESENT("Duplicate attribute value present for attribute %s"),
  ITEM_NAME_SHOULD_NOT_BE_BLANK("Item Name Should Not be Blank"),
  DOCUMENT_LIST_CANNOT_BE_EMPTY("Document links cannot be empty for brand authorisation request"),
  IPR_REGISTRATION_NUMBER_CANNOT_BE_EMPTY("Ipr registration number cannot be empty"),
  REJECTED_BRAND_AUTH_REQUEST_CANNOT_BE_EDITED("Rejected Brand Auth request cannot be edited"),
  BRAND_AUTH_WIP_NOT_FOUND("Brand Authorisation Wip Not Found"), NO_PENDING_ATTRIBUTES_TO_BE_MAPPED(
      "No pending Must show on PDP attributes to be mapped between product and category"),
  DUPLICATE_PRODUCT_CODE("Produk ini telah dibuat. Silakan cek notifikasi atau halaman Produk."),
  PRODUCT_SHOULD_HAVE_AT_LEAST_ONE_VARIANT("A product should have Atleast one variant"),
  ATTRIBUTE_TYPE_CANNOT_BE_DS_EXTRACTION("Given attribute type cannot be ds extraction"),
  ATTRIBUTE_TYPE_CANNOT_BE_DS_EXTRACTION_ERROR_CODE("ERR-DS-00001"),
  DS_ATTRIBUTE_NAME_CANNOT_BE_EMPTY("DS attribute name cannot be empty"),
  DS_ATTRIBUTE_NAME_CANNOT_BE_EMPTY_ERROR_CODE("ERR-DS-00002"),
  DUPLICATE_DS_ATTRIBUTE_NAME("Attribute with ds attributeName '%s' already exists"),
  DUPLICATE_DS_ATTRIBUTE_NAME_ERROR_CODE("ERR-DS-00003"),
  ATTRIBUTE_TYPE_CANNOT_BE_MULTI_LANGUAGE("Given attribute type cannot be multi language"),
  ATTRIBUTE_TYPE_CANNOT_BE_MULTI_LANGUAGE_ERROR_CODE("ERR-DS-00004"),
  PRODUCT_BATCH_SIZE_EXCEEDED("Product basic info batch size exceeded"),
  INVALID_EVENT_PAYLOAD_RECEIVED("Event payload was not valid"),
  PRODUCT_SKU_MUST_NOT_BE_BLANK("ProductSku should not be blank"),
  VIDEO_ID_MUST_NOT_BE_BLANK("Video Id must not be blank"),
  INVALID_ATTRIBUTE_VALUE("Invalid attribute value"),
  FINAL_VIDEO_URL_MUST_NOT_BE_BLANK("Final Video Url must not be blank"),
  PRODUCT_ITEM_UOM_INFO_REQUESTS_MUST_NOT_BE_EMPTY("Product Item UOM Info Requests must not be empty"),
  PRODUCT_ITEM_UOM_INFO_MUST_NOT_BE_EMPTY("Product Item UOM Info must not be empty"),
  DIMENSION_AND_UOM_UPDATE_REQUESTS_MUST_NOT_BE_EMPTY("Dimension and UOM Update Requests must not be empty");
  private String message;

  ErrorMessage(String message) {
    this.message = message;
  }

  public String getMessage() {
    return this.message;
  }
}
