package com.gdn.x.product.service.api;

import com.gdn.x.product.model.entity.SystemParameter;

public interface SystemParameterHistoryService {

  /**
   *
   * @param oldSystemParameter
   *
   *        save history delete will set only main value (storeId,variable,value, and description)
   *        from the oldSystemParam others attribute like (createdBy, createdDate, etc) will be
   *        generated by the time delete is triggered
   *
   */
  void saveHistoryDelete(SystemParameter oldSystemParameter);

  /**
   *
   * @param oldSystemParameter
   *
   *        save history update will set all value from old systemParameter except id
   */
  void saveHistoryUpdate(SystemParameter oldSystemParameter);
}
