package com.gdn.partners.pbp.commons.constants;

public interface EditedReviewTypeConstants {
  String CONTENT_EDIT = "CONTENT";
  String IMAGE_EDIT = "IMAGE";
  String IMAGE_REFRESH = "IMAGE_REFRESH";
  String CONTENT_REFRESH = "CONTENT_REFRESH";
  String RECONCILE_EDITED_TYPE = "RECONCILE_EDITED";
  String RECONCILE_CONTENT = "RECONCILE_CONTENT";
  String RECONCILE_IMAGE = "RECONCILE_IMAGE";
  String RECONCILE_REVISED_TYPE = "RECONCILE_REVISED";
  String RECONCILE_ACTIVE_PRODUCTS_TYPE = "RECONCILE_ACTIVE";
  String RETRY_BEFORE_APPROVAL_TYPE = "RETRY_BEFORE_APPROVAL";
  String RETRY_X_PRODUCT_ACTIVATION_BEFORE_APPROVAL = "RETRY_X_PRODUCT_ACTIVATION_BEFORE_APPROVAL";
  String RECONCILE_PRE_LIVE = "RECONCILE_PRE_LIVE";
}