@Library('jenkins-ci-automation@master') _
BlibliPipeline ([
    type : 'java21',
    application : [
      tribe : "seller",
      squad : "catalog",
      service_name : "x-product",
      dev_repo : "https://stash.gdn-app.com/scm/mta/product.git",
      deployment_repo : [nonprod : "ssh://git@stash.gdn-app.com:7999/nonprod-seller-catalog/xproduct.git"]
    ],
    sonar: [
      serverId : 'sonar9-gcp'
    ],
    trivy: [
         enabled: true,
         jira: true,
         projectkey_jira: "SHEN",
         assignee_jira: "Pradeep Reddy",
         component_jira: "X-Product",
         release_jira: "-",
         build_breaker: false
            ]
])
