@Library('jenkins-ci-automation@master') _

BlibliPipeline ([
  type : 'java21',
  application : [
    tribe : "seller",
    squad : "catalog",
    service_name : "pcu-external-api",
    dev_repo : "https://stash.gdn-app.com/scm/mta/pcu-external-api.git",
    deployment_repo : [nonprod : "ssh://git@stash.gdn-app.com:7999/nonprod-seller-catalog/pcu-external-api.git"]
    ],
  sonar : [
    serverId : 'sonar9-gcp'
    ],
    trivy: [
         enabled: true,
         jira: true,
         projectkey_jira: "SHEN",
         assignee_jira: "Pradeep Reddy",
         component_jira: "PCU External API",
         release_jira: "-",
         build_breaker: false
            ]
])
