@Library('jenkins-ci-automation@master') _

BlibliPipeline ([
  type : 'java21',
  application : [
    tribe : "seller",
    squad : "catalog",
    service_name : "product-analytics",
    dev_repo : "https://stash.gdn-app.com/projects/MTA/repos/product-analytics/browse",
    deployment_repo : [nonprod : "ssh://git@stash.gdn-app.com:7999/nonprod-seller-catalog/product-analytics.git"]
    ],
  sonar : [
    serverId : 'sonar9-gcp'
    ],
  trivy: [
     enabled: true,
     jira: true,
     projectkey_jira: "SHEN",
     assignee_jira: "Pradeep Reddy",
     component_jira: "product-analytics",
     release_jira: "-",
     build_breaker: false
          ]
])