@Library('jenkins-ci-automation@develop') _

BlibliPipeline([
    type: "java21",
    sonar: [
        serverId: "sonar9-gcp"
    ],
    deploy_branch_regex: "(master|release/.+)",
    application : [
        tribe : "seller",
        squad : "catalog",
        service_name : "aggregate-platform-module-product",
        dev_repo: "https://github.com/gdncomm/aggregate-platform-module-product.git",
        deployment_repo : [
            nonprod : "ssh://git@stash.gdn-app.com:7999/nonprod-seller-catalog/aggregate-platform-module-product.git"
        ]
    ],
    trivy: [
         enabled: true,
         jira: true,
         projectkey_jira: "SHEN",
         assignee_jira: "Pradeep Reddy",
         component_jira: "AGP Module Product",
         release_jira: "-",
         build_breaker: false
    ],
    test: [
        integration: [
            mongo: [
                enabled : true,
                version : '6.0',
                username: 'mongo',
                password: 'mongo',
                min_cpu: '8',
                min_memory: '4Gi',
                max_cpu: '8',
                max_memory: '16Gi'
            ],
            kafka: [
                enabled: true,
                version: '2.11-0.11.0.3',
                min_cpu: '8',
                min_memory: '4Gi',
                max_cpu: '8',
                max_memory: '16Gi'
            ],
            elasticsearch: [
                enabled: true,
                version: '6.4.1',
                min_cpu: '8',
                min_memory: '4Gi',
                max_cpu: '8',
                max_memory: '16Gi'
            ]
        ]
    ]
])
