package com.gdn.mta.product.commons.constant;

public enum UpdateProductActivity {
  SELLING_PRICE("Ubah harga jual"),
  NORMAL_PRICE("Ubah harga normal"),
  STOCK_VALUE("Ubah stock"),
  PRE_ORDER_QUOTA("Ubah kuota pre order"),
  SYNC_STOCK("Ubah sinkronisasi stock"),
  BUYABLE("Ubah dapat dibeli"),
  DISPLAYABLE("Ubah dapat ditampilkan"),
  CNC_BUYABLE("Ubah dapat cnc dibeli"),
  CNC_DISPLAYABLE("Ubah dapat cnc ditampilkan"),
  PRODUCT_NAME("Ubah nama produk"),
  PRODUCT_DESC("Ubah deskripsi produk"),
  OFFLINE_TO_ONLINE("Ubah offline to online"),
  MERCHANT_SKU("Ubah merchant sku"),
  SYNC_CONTENT("Ubah sinkronisasi konten"),
  ARCHIVE("Ubah diarsipkan"),
  LATE_FULFILLMENT("Ubah auto cancel"),
  PRODUCT_TYPE("Ubah tipe produk"),
  LENGTH("Ubah panjang"),
  WIDTH("Ubah lebar"),
  HEIGHT("Ubah tinggi"),
  WEIGHT("Ubah berat"),
  DG_LEVEL("Ubah DG level"),
  PICK_POINT_CODE("Ubah pickup point code"),
  MINIMUM_STOCK("Ubah minimum stock"),
  URL_VIDEO("Ubah url video"),
  USP("Ubah USP"),
  LOGISTIC("Ubah logistic"),
  PRE_ORDER("Ubah pre order"),
  BUYABLE_SCHEDULE("Ubah buyable schedule"),
  DISCOVERABLE_SCHEDULE("Ubah discoverable schedule"),
  INSTALLATION_FLAG("Ubah installation flag"),
  SUSPENSION("Ubah suspend"),
  ATTRIBUTES("Ubah attribute"),
  WHOLE_PRICE_FLAG("Status grosir"),
  UPDATE_WHOLE_SALE_RULES("Harga grosir diperbarui"),
  ADD_WHOLE_SALE_RULES("Harga grosir ditambahkan"),
  SYNC_NORMAL_PRICE("Sync harga normal"),
  SYNC_SELLING_PRICE("Sync harga jual"),
  INITIAL_NORMAL_PRICE("Harga normal awal"),
  INITIAL_SELLING_PRICE("Harga jual awal"),
  UPC_CODE("Ubah upc code"),
  IMAGE_ADDED("Image added"),
  IMAGE_DELETED("Image deleted"),
  IMAGE_UPDATED("Image updated"),
  STOCK_MINIMUM_VALUE("Ubah minimum stock"),
  APPLICABLE_FOR_VAT("Applicable for vat"),
  CNC("Ubah CNC"),
  FBB_ACTIVATED("Updated FBB to true"),
  FBB_DEACTIVATED("Updated FBB to false and markForDelete to true"),
  PICKUP_POINT_ADDED("New pickup point added"),
  PICKUP_POINT_DELETED("pickup point deleted"),
  FREE_SAMPLE("Free sample updated"),
  ONLINE_FLAG("Online flag updated"),
  FBB_FLAG("FBB flag updated"),
  AUTO_CATEGORY_CHANGE("perubahan kategori otomatis"),
  ITEM_ADDED("Variant added"),
  ITEM_DELETED("Variant deleted"),
  B2B_BUYABLE("B2b buyable flag updated"),
  B2B_DISCOVERABLE("B2b discoverable flag updated"),
  B2B_MANAGED("B2b managed flag updated"),
  B2B_PRICE("B2b price updated"),
  B2C_ACTIVATED("B2c activated flag updated"),
  B2B_ACTIVATED("B2b activated flag updated"),
  INITIAL_B2B_SALES_CHANNEL("Initial B2B sales channel"),
  INITIAL_B2B_BUYABLE("Initial B2B buyable"),
  INITIAL_B2B_DISCOVERABLE("Initial B2B discoverable"),
  INITIAL_B2B_MANAGED("Initial B2B managed"),
  INITIAL_B2B_BASE_PRICE("Initial B2B base price"),
  LENGTH_CHANGE("LENGTH_CHANGE"),
  WIDTH_CHANGE("WIDTH_CHANGE"),
  HEIGHT_CHANGE("HEIGHT_CHANGE"),
  WEIGHT_CHANGE("WEIGHT_CHANGE"),
  SHIPPING_WEIGHT_CHANGE("SHIPPING_WEIGHT_CHANGE"),
  BUNDLE_RECIPE_CHANGE("BUNDLE_RECIPE_CHANGE"),
  SIZE_CHART_CHANGE("ubah size chart"),
  EXTERNAL_CATEGORY_CHANGE("ubah Kategori");

  private String desc;

  UpdateProductActivity(String desc) {
    this.desc = desc;
  }

  public String getDesc() {
    return desc;
  }
}
