package com.gdn.mta.product.enums;

public enum L3InfoUpdateChangeType {
  PRODUCT_NAME_UPDATE, INSTORE_UPDATE, DESCRIPTION_UPDATE
  , COMMON_IMAGE_UPDATE, VIDEO_UPDATE, PRODUCT_TYPE_UPDATE,
  DIMENSIONS_UPDATE, SIZE_CHART_UPDATE, YOUTUBE_URL_UPDATE
}
