package com.gdn.x.mta.distributiontask.rest.model.constant;

public enum WorkflowWebState {
  UNASSIGNED,
  IN_REVIEW,
  CONTENT_APPROVED,
  IMAGES_APPROVED,
  CONTENT_AND_IMAGE_APPROVED,
  CONTENT_REJECTED,
  IMAGE_REJECTED,
  REJECTED,
  QC_REJECTED,
  PASSED,
  EXCEEDED_SLA,
  CONTENT_NEED_CORRECTION,
  IMAGE_NEED_CORRECTION,
  CONTENT_AND_IMAGE_NEED_CORRECTION,
  NEED_CORRECTION
}
